{{- if .Values.persistence.enabled -}}
{{- $fullName := include "generic-service.fullname" . -}}
{{- range $volumeName, $val := .Values.persistence.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-{{ $volumeName }}
spec:
  storageClassName: {{ $val.storageClass }}
  accessModes:
  {{- if $val.accessModes }}
  {{- toYaml $val.accessModes | nindent 2 }}
  {{- else }}
  - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: {{ $val.storage }}
{{- end }}
{{- end }}
