{{- $fullName := include "generic-service.fullname" . -}}
{{- range $secretName, $val := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-{{ $secretName }}
stringData:
{{- range $secretDataName, $secretDataVal := $val }}
  {{ $secretDataName }}: |
    {{- toYaml $secretDataVal | b64enc | nindent 4}}
{{- end }}
{{- end }}
