{{- $fullName := include "generic-service.fullname" . -}}
{{- range $secretName, $val := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-{{ $secretName }}
data:
  {{- toYaml $val | nindent 2}}
{{- end }}
